name       : materia-gtk-theme
version    : '20180110'
release    : 3
source     :
    - https://github.com/nana-4/materia-theme/archive/v20180110.tar.gz : 44e2bfd5abb475a448f3aa9ad9b1d57cf86e6583483b45656a7516fd8070f8f9
license    : GPL-2.0
component  : desktop.theme
summary    : A Material Design-like theme for GNOME/GTK+ based desktop environments
description: |
    Materia (formerly Flat-Plat) is a Material Design theme for GNOME/GTK+
    based desktop environments.

    It supports GTK+ 3, GTK+ 2, GNOME Shell, Budgie, MATE, LightDM, GDM,
    Chrome theme, etc.
replaces   :
    - flat-plat-gtk-theme
    - compact : flat-plat-gtk-theme-compact
    - dark : flat-plat-gtk-theme-dark
    - dark-compact : flat-plat-gtk-theme-compact
    - light : flat-plat-gtk-theme-light
    - light-compact : flat-plat-gtk-theme-light-compact
patterns   :
    - compact : /usr/share/themes/*-compact
    - dark : /usr/share/themes/*-dark
    - dark-compact : /usr/share/themes/*-dark-compact
    - light : /usr/share/themes/*-light
    - light-compact : /usr/share/themes/*-light-compact
install    : |
    destdir=$installdir ./install.sh

    rm -rf $installdir/usr/share/themes/*/{unity,xfwm4}

    pushd $installdir/usr/share/themes
        ln -s Materia Flat-Plat
        ln -s Materia-compact Flat-Plat-compact
        ln -s Materia-dark Flat-Plat-dark
        ln -s Materia-dark-compact Flat-Plat-dark-compact
        ln -s Materia-light Flat-Plat-light
        ln -s Materia-light-compact Flat-Plat-light-compact
    popd
