name       : flat-plat-gtk-theme
version    : 20170323
release    : 1
source     :
    - https://github.com/nana-4/Flat-Plat/archive/v20170323.tar.gz : 6599db2ed4b7c040ceaf9e9e17c1716b3d196537872c31f4a90a3282dda6741b
license    : GPL-2.0
component  : desktop.theme
summary    : A Material Design-like theme for GNOME/GTK+ based desktop environments.
description: |
    A Material Design-like theme for GNOME/GTK+ based desktop environments.
install    : |
    destdir=$installdir ./install.sh
    rm -rf $installdir/usr/share/themes/*/unity
patterns   :
    - compact:
        - /usr/share/themes/Flat-Plat-compact
    - dark:
        - /usr/share/themes/Flat-Plat-dark
    - dark-compact:
        - /usr/share/themes/Flat-Plat-dark-compact
    - light:
        - /usr/share/themes/Flat-Plat-light
    - light-compact:
        - /usr/share/themes/Flat-Plat-light-compact