name       : materia-gtk-theme
version    : '20181115'
release    : 7
source     :
    - https://github.com/nana-4/materia-theme/archive/v20181125.tar.gz : 50066e40cbfc8e00a995fb73522d1cb6b21b236fa03b4463d9e25a0f5c4fe5bc
license    : GPL-2.0-or-later
component  : desktop.theme
summary    : A Material Design-like theme for GNOME/GTK+ based desktop environments
description: |
    Materia (formerly Flat-Plat) is a Material Design theme for GNOME/GTK+
    based desktop environments.

    It supports GTK+ 3, GTK+ 2, GNOME Shell, Budgie, MATE, LightDM, GDM,
    Chrome theme, etc.
replaces   :
    - flat-plat-gtk-theme
    - compact : flat-plat-gtk-theme-compact
    - dark : flat-plat-gtk-theme-dark
    - dark-compact : flat-plat-gtk-theme-dark-compact
    - light : flat-plat-gtk-theme-light
    - light-compact : flat-plat-gtk-theme-light-compact
patterns   :
    - compact : /usr/share/themes/*-compact
    - dark : /usr/share/themes/*-dark
    - dark-compact : /usr/share/themes/*-dark-compact
    - light : /usr/share/themes/*-light
    - light-compact : /usr/share/themes/*-light-compact
install    : |
    install -d -m 00755 $installdir/usr/share/themes

    ./install.sh --dest $installdir/usr/share/themes

    rm -rf $installdir/usr/share/themes/*/{unity,xfwm4}

    pushd $installdir/usr/share/themes
        ln -s Materia Flat-Plat
        ln -s Materia-compact Flat-Plat-compact
        ln -s Materia-dark Flat-Plat-dark
        ln -s Materia-dark-compact Flat-Plat-dark-compact
        ln -s Materia-light Flat-Plat-light
        ln -s Materia-light-compact Flat-Plat-light-compact
    popd
